version: '3.7'

services:
  postgres_backend_aee:
    container_name: postgres_backend_aee
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DBNAME}
      PG_DATA: /var/lib/postgresql/data
    env_file:
      - .env
    command: -p ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  pgdata:
