version: "3"

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5433:5432"
    container_name: "postgres"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: backend_special
      POSTGRES_PASSWORD: 123

volumes:
  pgdata:
